ERROR:root:(1 points) Checking WR times: Does the final plot have at least the elements in a basic plot?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking WR times: Does the final plot contain a main title, an x-label and a y-label?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking WR times: Does the final plot have the extension of line?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking WR times: Are there two vertical lines?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking WR times: Are the vertical lines grey?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking WR times: Are there text names next to the lines?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Medals: Is the plot not too cluttered?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Medals: Are there labels in the plot?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Medals: Are there circles and points in the plot?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Medals: Are there five labelled circles in the plot?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Medals: Does the basic plot look fine?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Map: Does the plot look good?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(2 points) Checking Map: Are the circles of decent size?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Map: Are the colors reasonable?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Barplot: Did the student try both versions of the barplot?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Barplot: Are the bars side-by-side?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(2 points) Checking Barplot: Are the labels rotated?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
ERROR:root:(1 points) Checking Barplot: Does the title and the plot look okay?
ERROR:root:... Expecting: False
ERROR:root:... But got:   n
INFO:root:Executed R('load(\'../../instructor/assignments/hw2/hw2-tests.rda\')')
INFO:root:(1 points) R('all.equal(n.wr, sol$n.wr, check.attributes=F)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(wr.name, sol$wr.name, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   current is not list-like
INFO:root:(1 points) R('all.equal(times_sec, sol$times_sec, check.attributes=F)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(new_year, sol$new_year, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(new_year, sol$new_year, check.attributes = F) : 
  object 'new_year' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(new_year, sol$new_year, check.attributes = F) : 
  object 'new_year' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(new_year, sol$new_year, check.attributes = F) : 
  object 'new_year' not found

ERROR:root:(1 points) Checking R('all.equal(wr1500m, sol$wr1500m, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Length mismatch: comparison on first 5 components
ERROR:root:(1 points) Checking R('all.equal(wr_1998, sol$wr_1998, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1998, sol$wr_1998, check.attributes = F) : 
  object 'wr_1998' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1998, sol$wr_1998, check.attributes = F) : 
  object 'wr_1998' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1998, sol$wr_1998, check.attributes = F) : 
  object 'wr_1998' not found

ERROR:root:(1 points) Checking R('all.equal(wr_1944, sol$wr_1994, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1944, sol$wr_1994, check.attributes = F) : 
  object 'wr_1944' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1944, sol$wr_1994, check.attributes = F) : 
  object 'wr_1944' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(wr_1944, sol$wr_1994, check.attributes = F) : 
  object 'wr_1944' not found

ERROR:root:(1 points) Checking R('all.equal(n.athletes, sol$n.athletes, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.athletes, sol$n.athletes, check.attributes = F) : 
  object 'n.athletes' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.athletes, sol$n.athletes, check.attributes = F) : 
  object 'n.athletes' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.athletes, sol$n.athletes, check.attributes = F) : 
  object 'n.athletes' not found

ERROR:root:(1 points) Checking R('all.equal(n.women, sol$n.women, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.women, sol$n.women, check.attributes = F) : 
  object 'n.women' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.women, sol$n.women, check.attributes = F) : 
  object 'n.women' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.women, sol$n.women, check.attributes = F) : 
  object 'n.women' not found

ERROR:root:(1 points) Checking R('all.equal(frac.women, sol$frac.women, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(frac.women, sol$frac.women, check.attributes = F) : 
  object 'frac.women' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(frac.women, sol$frac.women, check.attributes = F) : 
  object 'frac.women' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(frac.women, sol$frac.women, check.attributes = F) : 
  object 'frac.women' not found

ERROR:root:(1 points) Checking R('all.equal(n.sports, sol$n.sports, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.sports, sol$n.sports, check.attributes = F) : 
  object 'n.sports' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.sports, sol$n.sports, check.attributes = F) : 
  object 'n.sports' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2-2.5.6-py2.7-macosx-10.10-intel.egg/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.sports, sol$n.sports, check.attributes = F) : 
  object 'n.sports' not found

INFO:root:You got a 2 out of 31.
